abils = [['Adaptability ' , 'Powers up moves of the same type. ' ] , 
['Aerilate ' , 'Turns Normal-type moves into Flying-type moves. ' ] , 
['Aftermath ' , 'Damages the attacker landing the finishing hit. ' ] , 
['Air Lock ' , 'Eliminates the effects of weather. ' ] , 
['Analytic ' , 'Boosts move power when the Pokemon moves last. ' ] , 
['Anger Point ' , 'Maxes Attack after taking a critical hit. ' ] , 
['Anticipation ' , 'Senses a foe\'s dangerous moves. ' ] , 
['Arena Trap ' , 'Prevents the foe from fleeing. ' ] , 
['Aroma Veil ' , 'Protects allies from attacks that limit their move choices. ' ] , 
['Aura Break ' , 'The effects of \"Aura\" Abilities are reversed. ' ] , 
['Bad Dreams ' , 'Reduces a sleeping foe\'s HP. ' ] , 
['Battery ' , 'Raises power of teammate\'s Special moves. ' ] , 
['Battle Armor ' , 'The Pokemon is protected against critical hits. ' ] , 
['Battle Bond ' , 'Transform into Ash-Greninja after causing opponent to faint. ' ] , 
['Beast Boost ' , 'The Pokemon boosts its most proficient stat each time it knocks out a Pokemon. ' ] , 
['Berserk ' , 'Raises Special Attack when HP drops below half. ' ] , 
['Big Pecks ' , 'Protects the Pokemon from Defense-lowering attacks. ' ] , 
['Blaze ' , 'Powers up Fire-type moves in a pinch. ' ] , 
['Bulletproof ' , 'Protects the Pokemon from ball and bomb moves. ' ] , 
['Cheek Pouch ' , 'Restores additional HP when a Berry is consumed. ' ] , 
['Chlorophyll ' , 'Boosts the Pokemon\'s Speed in sunshine. ' ] , 
['Clear Body ' , 'Prevents other Pokemon from lowering its stats. ' ] , 
['Cloud Nine ' , 'Eliminates the effects of weather. ' ] , 
['Color Change ' , 'Changes the Pokemon\'s type to the foe\'s move. ' ] , 
['Comatose ' , 'Prevents all status conditions except Sleep. ' ] , 
['Competitive ' , 'Raises Special Attack when the Pokemon\'s stats are lowered. ' ] , 
['Compound Eyes ' , 'The Pokemon\'s accuracy is boosted. ' ] , 
['Contrary ' , 'Makes stat changes have an opposite effect. ' ] , 
['Corrosion ' , 'The Pokemon can poison Steel and Poison types. ' ] , 
['Cursed Body ' , 'May disable a move used on the Pokemon. ' ] , 
['Cute Charm ' , 'Contact with the Pokemon may cause infatuation. ' ] , 
['Damp ' , 'Prevents the use of self-destructing moves. ' ] , 
['Dancer ' , 'Copies the foe\'s Dance moves. ' ] , 
['Dark Aura ' , 'Raises power of Dark type moves for all Pokemon in battle. ' ] , 
['Dazzling ' , 'Protects the Pokemon from high-priority moves. ' ] , 
['Defeatist ' , 'Lowers stats when HP drops below half. ' ] , 
['Defiant ' , 'When its stats are lowered its Attack increases. ' ] , 
['Delta Stream ' , 'Creates strong winds when the ability activates. ' ] , 
['Desolate Land ' , 'Turns the sunlight extremely harsh when the ability activates. ' ] , 
['Disguise ' , 'Avoids damage for one turn. ' ] , 
['Download ' , 'Adjusts power according to a foe\'s defenses. ' ] , 
['Drizzle ' , 'The Pokemon makes it rain when it enters a battle. ' ] , 
['Drought ' , 'Turns the sunlight harsh when the Pokemon enters a battle. ' ] , 
['Dry Skin ' , 'Reduces HP if it is hot. Water restores HP. ' ] , 
['Early Bird ' , 'The Pokemon awakens quickly from sleep. ' ] , 
['Effect Spore ' , 'Contact may poison or cause paralysis or sleep. ' ] , 
['Electric Surge ' , 'The Pokemon creates an Electric Terrain when it enters a battle. ' ] , 
['Emergency Exit ' , 'The Pokemon, sensing danger, switches out when its HP becomes half or less. ' ] , 
['Fairy Aura ' , 'Raises power of Fairy type moves for all Pokemon in battle. ' ] , 
['Filter ' , 'Reduces damage from supereffective attacks. ' ] , 
['Flame Body ' , 'Contact with the Pokemon may burn the attacker. ' ] , 
['Flare Boost ' , 'Powers up special attacks when burned. ' ] , 
['Flash Fire ' , 'It powers up Fire-type moves if it\'s hit by one. ' ] , 
['Flower Gift ' , 'Powers up party Pokemon when it is sunny. ' ] , 
['Flower Veil ' , 'Prevents lowering of ally Grass-type Pokemon\'s stats. ' ] , 
['Fluffy ' , 'Reduces damage from contact moves, but doubles damage from Fire-type moves. ' ] , 
['Forecast ' , 'Castform transforms with the weather. ' ] , 
['Forewarn ' , 'Determines what moves a foe has. ' ] , 
['Friend Guard ' , 'Reduces damage done to allies. ' ] , 
['Frisk ' , 'The Pokemon can check a foe\'s held item. ' ] , 
['Full Metal Body ' , 'Prevents other Pokemon from lowering its stats. ' ] , 
['Fur Coat ' , 'Reduces damage from physical moves. ' ] , 
['Gale Wings ' , 'Gives priority to Flying-type moves. ' ] , 
['Galvanize ' , 'Normal-type moves become Electric-type moves. The power of those moves is booste ' ],  
['Gluttony ' , 'Encourages the early use of a held Berry. ' ] , 
['Gooey ' , 'Contact with the Pokemon lowers the attacker\'s Speed stat. ' ] , 
['Grass Pelt ' , 'Boosts the Defense stat in Grassy Terrain. ' ] , 
['Grassy Surge ' , 'The Pokemon creates a Grassy Terrain when it enters a battle. ' ] , 
['Guts ' , 'Boosts Attack if there is a status problem. ' ] , 
['Harvest ' , 'May create another Berry after one is used. ' ] , 
['Healer ' , 'May heal an ally\'s status conditions. ' ] , 
['Heatproof ' , 'Weakens the power of Fire-type moves. ' ] , 
['Heavy Metal ' , 'Doubles the Pokemon\'s weight. ' ] , 
['Honey Gather ' , 'The Pokemon may gather Honey from somewhere. ' ] , 
['Huge Power ' , 'Raises the Pokemon\'s Attack stat. ' ] , 
['Hustle ' , 'Boosts the Attack stat, but lowers accuracy. ' ] , 
['Hydration ' , 'Heals status problems if it is raining. ' ] , 
['Hyper Cutter ' , 'Prevents other Pokemon from lowering Attack stat. ' ] , 
['Ice Body ' , 'The Pokemon gradually regains HP in a hailstorm. ' ] , 
['Illuminate ' , 'Raises the likelihood of meeting wild Pokemon. ' ] , 
['Illusion ' , 'Comes out disguised as the Pokemon in back. ' ] , 
['Immunity ' , 'Prevents the Pokemon from getting poisoned. ' ] , 
['Imposter ' , 'It transforms itself into the Pokemon it is facing. ' ] , 
['Infiltrator ' , 'Passes through the foe\'s barrier and strikes. ' ] , 
['Innards Out ' , 'Deals damage upon fainting. ' ] , 
['Inner Focus ' , 'The Pokemon is protected from flinching. ' ] , 
['Insomnia ' , 'Prevents the Pokemon from falling asleep. ' ] , 
['Intimidate ' , 'Lowers the foe\'s Attack stat. ' ] , 
['Iron Barbs ' , 'Inflicts damage to the Pokemon on contact. ' ] , 
['Iron Fist ' , 'Boosts the power of punching moves. ' ] , 
['Justified ' , 'Raises Attack when hit by a Dark-type move. ' ] , 
['Keen Eye ' , 'Prevents other Pokemon from lowering accuracy. ' ] , 
['Klutz ' , 'The Pokemon can\'t use any held items. ' ] , 
['Leaf Guard ' , 'Prevents problems with status in sunny weather. ' ] , 
['Levitate ' , 'Gives immunity to Ground type moves. ' ] , 
['Light Metal ' , 'Halves the Pokemon\'s weight. ' ] , 
['Lightning Rod ' , 'Draws in all Electric-type moves to up Sp. Attack. ' ] , 
['Limber ' , 'The Pokemon is protected from paralysis. ' ] , 
['Liquid Ooze ' , 'Damages attackers using any draining move. ' ] , 
['Liquid Voice ' , 'All sound-based moves become Water-type moves. ' ] , 
['Long Reach ' , 'The Pokemon uses its moves without making contact with the target. ' ] , 
['Magic Bounce ' , 'Reflects status- changing moves. ' ] , 
['Magic Guard ' , 'The Pokemon only takes damage from attacks. ' ] , 
['Magician ' , 'The Pokemon steals the held item of a Pokemon it hits with a move. ' ] , 
['Magma Armor ' , 'Prevents the Pokemon from becoming frozen. ' ] , 
['Magnet Pull ' , 'Prevents Steel-type Pokemon from escaping. ' ] , 
['Marvel Scale ' , 'Ups Defense if there is a status problem. ' ] , 
['Mega Launcher ' , 'Boosts the power of aura and pulse moves. ' ] , 
['Merciless ' , 'The Pokemon’s attacks become critical hits if the target is poisoned. ' ] , 
['Minus ' , 'Ups Sp. Atk if another Pokemon has Plus or Minus. ' ] , 
['Misty Surge ' , 'The Pokemon creates a Misty Terrain when it enters a battle. ' ] , 
['Mold Breaker ' , 'Moves can be used regardless of Abilities. ' ] , 
['Moody ' , 'Raises one stat and lowers another. ' ] , 
['Motor Drive ' , 'Raises Speed if hit by an Electric-type move. ' ] , 
['Moxie ' , 'Boosts Attack after knocking out any Pokemon. ' ] , 
['Multiscale ' , 'Reduces damage when HP is full. ' ] , 
['Multitype ' , 'Changes type to match the held Plate. ' ] , 
['Mummy ' , 'Contact with this Pokemon spreads this Ability. ' ] , 
['Natural Cure ' , 'All status problems heal when it switches out. ' ] , 
['No Guard ' , 'Ensures attacks by or against the Pokemon land. ' ] , 
['Normalize ' , 'All the Pokemon\'s moves become the Normal type. ' ] , 
['Oblivious ' , 'Prevents it from becoming infatuated. ' ] , 
['Overcoat ' , 'Protects the Pokemon from damage from weather. ' ] , 
['Overgrow ' , 'Powers up Grass-type moves in a pinch. ' ] , 
['Own Tempo ' , 'Prevents the Pokemon from becoming confused. ' ] , 
['Parental Bond ' , 'Allows the Pokemon to attack twice. ' ] , 
['Pickpocket ' , 'Steals an item when hit by another Pokemon. ' ] , 
['Pickup ' , 'The Pokemon may pick up items. ' ] , 
['Pixilate ' , 'Turns Normal-type moves into Fairy-type moves. ' ] , 
['Plus ' , 'Ups Sp. Atk if another Pokemon has Plus or Minus. ' ] , 
['Poison Heal ' , 'Restores HP if the Pokemon is poisoned. ' ] , 
['Poison Point ' , 'Contact with the Pokemon may poison the attacker. ' ] , 
['Poison Touch ' , 'May poison targets when a Pokemon makes contact. ' ] , 
['Power Construct ' , 'Changes form when HP drops below half. ' ] , 
['Power of Alchemy ' , 'The Pokemon copies the Ability of a defeated ally. ' ] , 
['Prankster ' , 'Gives priority to a status move. ' ] , 
['Pressure ' , 'The Pokemon raises the foe\'s PP usage. ' ] , 
['Primordial Sea ' , 'Makes it rain heavily when the ability activates. ' ] , 
['Prism Armor ' , 'Reduces the power of supereffective attacks taken. ' ] , 
['Protean ' , 'Changes the Pokemon\'s type to its last used move. ' ] , 
['Psychic Surge ' , 'The Pokemon creates a Psychic Terrain when it enters a battle. ' ] , 
['Pure Power ' , 'Raises the Pokemon\'s Attack stat. ' ] , 
['Queenly Majesty ' , 'Prevents use of priority moves. ' ] , 
['Quick Feet ' , 'Boosts Speed if there is a status problem. ' ] , 
['Rain Dish ' , 'The Pokemon gradually regains HP in rain. ' ] , 
['Rattled ' , 'Bug, Ghost or Dark type moves scare it and boost its Speed. ' ] , 
['Receiver ' , 'Inherits an ally\'s ability when it faints. ' ] , 
['Reckless ' , 'Powers up moves that have recoil damage. ' ] , 
['Refrigerate ' , 'Turns Normal-type moves into Ice-type moves. ' ] , 
['Regenerator ' , 'Restores a little HP when withdrawn from battle. ' ] , 
['Rivalry ' , 'Deals more damage to a Pokemon of same gender. ' ] , 
['RKS System ' , 'Changes type depending on held item. ' ] , 
['Rock Head ' , 'Protects the Pokemon from recoil damage. ' ] , 
['Rough Skin ' , 'Inflicts damage to the attacker on contact. ' ] , 
['Run Away ' , 'Enables a sure getaway from wild Pokemon. ' ] , 
['Sand Force ' , 'Boosts certain move\'s power in a sandstorm. ' ] , 
['Sand Rush ' , 'Boosts the Pokemon\'s Speed in a sandstorm. ' ] , 
['Sand Stream ' , 'The Pokemon summons a sandstorm in battle. ' ] , 
['Sand Veil ' , 'Boosts the Pokemon\'s evasion in a sandstorm. ' ] , 
['Sap Sipper ' , 'Boosts Attack when hit by a Grass-type move. ' ] , 
['Schooling ' , 'Changes Wishiwashi to School form. ' ] , 
['Scrappy ' , 'Enables moves to hit Ghost-type Pokemon. ' ] , 
['Serene Grace ' , 'Boosts the likelihood of added effects appearing. ' ] , 
['Shadow Shield ' , 'Reduces damage when HP is full. ' ] , 
['Shadow Tag ' , 'Prevents the foe from escaping. ' ] , 
['Shed Skin ' , 'The Pokemon may heal its own status problems. ' ] , 
['Sheer Force ' , 'Removes added effects to increase move damage. ' ] , 
['Shell Armor ' , 'The Pokemon is protected against critical hits. ' ] , 
['Shield Dust ' , 'Blocks the added effects of attacks taken. ' ] , 
['Shields Down ' , 'Changes stats when HP drops below half. ' ] , 
['Simple ' , 'Doubles all stat changes. ' ] , 
['Skill Link ' , 'Increases the frequency of multi-strike moves. ' ] , 
['Slow Start ' , 'Temporarily halves Attack and Speed. ' ] , 
['Slush Rush ' , 'Boosts the Pokemon’s Speed stat in a hailstorm. ' ] , 
['Sniper ' , 'Powers up moves if they become critical hits. ' ] , 
['Snow Cloak ' , 'Raises evasion in a hailstorm. ' ] , 
['Snow Warning ' , 'The Pokemon summons a hailstorm in battle. ' ] , 
['Solar Power ' , 'In sunshine, Sp. Atk is boosted but HP decreases. ' ] , 
['Solid Rock ' , 'Reduces damage from supereffective attacks. ' ] , 
['Soul-Heart ' , 'Raises Special Attack when an ally faints. ' ] , 
['Soundproof ' , 'Gives immunity to \"sound-based\" moves. ' ] , 
['Speed Boost ' , 'Its Speed stat is gradually boosted. ' ] , 
['Stakeout ' , 'Deals double damage to Pokemon switching in. ' ] , 
['Stall ' , 'The Pokemon moves after all other Pokemon do. ' ] , 
['Stamina ' , 'Raises Defense when attacked. ' ] , 
['Stance Change ' , 'Changes form depending on moves used. ' ] , 
['Static ' , 'Contact with the Pokemon may cause paralysis. ' ] , 
['Steadfast ' , 'Raises Speed each time the Pokemon flinches. ' ] , 
['Steelworker ' , 'Powers up Steel-type moves. ' ] , 
['Stench ' , 'The stench may cause the target to flinch. ' ] , 
['Sticky Hold ' , 'Protects the Pokemon from item theft. ' ] , 
['Storm Drain ' , 'Draws in all Water-type moves to up Sp. Attack. ' ] , 
['Strong Jaw ' , 'Boosts the power of biting moves. ' ] , 
['Sturdy ' , 'It cannot be knocked out with one hit. ' ] , 
['Suction Cups ' , 'Negates all moves that force switching out. ' ] , 
['Super Luck ' , 'Heightens the critical-hit ratios of moves. ' ] , 
['Surge Surfer ' , 'Doubles Speed during Electric Terrain. ' ] , 
['Swarm ' , 'Powers up Bug-type moves in a pinch. ' ] , 
['Sweet Veil ' , 'Prevents the Pokemon and allies from falling asleep. ' ] , 
['Swift Swim ' , 'Boosts the Pokemon\'s Speed in rain. ' ] , 
['Symbiosis ' , 'The Pokemon can pass an item to an ally. ' ] , 
['Synchronize ' , 'Passes a burn, poison, or paralysis to the foe. ' ] , 
['Tangled Feet ' , 'Raises evasion if the Pokemon is confused. ' ] , 
['Tangling Hair ' , 'Contact with the Pokemon lowers the attacker’s Speed stat. ' ] , 
['Technician ' , 'Powers up the Pokemon\'s weaker moves. ' ] , 
['Telepathy ' , 'Anticipates an ally\'s attack and dodges it. ' ] , 
['Teravolt ' , 'Moves can be used regardless of Abilities. ' ] , 
['Thick Fat ' , 'Ups resistance to Fire- and Ice-type moves. ' ] , 
['Tinted Lens ' , 'Powers up \"not very effective\" moves. ' ] , 
['Torrent ' , 'Powers up Water-type moves in a pinch. ' ] , 
['Tough Claws ' , 'Boosts the power of contact moves. ' ] , 
['Toxic Boost ' , 'Powers up physical attacks when poisoned. ' ] , 
['Trace ' , 'The Pokemon copies a foe\'s Ability. ' ] , 
['Triage ' , 'Gives priority to restorative moves. ' ] , 
['Truant ' , 'Pokemon can\'t attack on consecutive turns. ' ] , 
['Turboblaze ' , 'Moves can be used regardless of Abilities. ' ] , 
['Unaware ' , 'Ignores any stat changes in the Pokemon. ' ] , 
['Unburden ' , 'Raises Speed if a held item is used. ' ] , 
['Unnerve ' , 'Makes the foe nervous and unable to eat Berries. ' ] , 
['Victory Star ' , 'Boosts the accuracy of its allies and itself. ' ] , 
['Vital Spirit ' , 'Prevents the Pokemon from falling asleep. ' ] , 
['Volt Absorb ' , 'Restores HP if hit by an Electric-type move. ' ] , 
['Water Absorb ' , 'Restores HP if hit by a Water-type move. ' ] , 
['Water Bubble ' , 'Lowers the power of Fire-type moves done to the Pokemon and prevents the Pokemon ' ] ,
['Water Compaction ' , 'Sharply raises Defense when hit by a Water-type move. ' ] , 
['Water Veil ' , 'Prevents the Pokemon from getting a burn. ' ] , 
['Weak Armor ' , 'Physical attacks lower Defense and raise Speed. ' ] , 
['White Smoke ' , 'Prevents other Pokemon from lowering its stats. ' ] , 
['Wimp Out ' , 'Switches out when HP drops below half. ' ] , 
['Wonder Guard ' , 'Only supereffective moves will hit. ' ] , 
['Wonder Skin ' , 'Makes status-changing moves more likely to miss. ' ] , 
['Zen Mode ' , 'Changes form when HP drops below half. ' ]]
